### RankNet-klap

compare RankNet results with ml methods

sync the test dataset of the two methods



In [4]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import math


In [22]:
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn import metrics
import indycar.model.stint_simulator_shortterm_pitmodel as stint

INFO:root:Using GPU
INFO:root:Using GPU
INFO:root:Using GPU
INFO:root:Using GPU
INFO:root:Using GPU


In [6]:
def evaluate(test_y, pred_y):
    mae = metrics.mean_absolute_error(test_y, pred_y) 
    rmse = math.sqrt(metrics.mean_squared_error(test_y, pred_y))
    r2 = metrics.r2_score(test_y, pred_y)
    print('rmse=%.2f, mae=%.2f, r2=%.2f'%(rmse, mae, r2))
    return mae,rmse, r2
    
def regressor_model(name='svr'):
    ### test learning models
    print('[*] predict with %s model'%name)
    clf = get_regressor(name)
    clf.fit(train_x, train_y)

    pred_y = clf.predict(test_x)
    
    #int only
    pred_y = pred_y.astype(int)
    
    score = evaluate(test_y, pred_y)
    return score

In [25]:
dfml = pd.read_csv('test_db_ml_l2_2018.csv')
dfranknet = pd.read_csv('result-shorterm_l2_2018_oracle.csv')
carlist = set(list(dfml['carno'].values))
dfpits = []
for car in carlist:
    pitlaps = dfml[dfml['carno']==car].startlap
    dfpits.append(dfranknet[(dfranknet['carno']==car) & (dfranknet['startlap'].isin(pitlaps))])
    
df_ranknet = pd.concat(dfpits)
stint.get_evalret(df_ranknet)


model: acc={0.70}, mae={2.46}, rmse={4.37},r2={-0.66}, 
            naive: acc={0.26}, mae={3.73}, rmse={5.65},r2={0.58}


array([[ 0.70440252,  2.4591195 ,  4.37186545, -0.66177512],
       [ 0.26415094,  3.72955975,  5.65184892,  0.5774171 ]])

In [26]:
dfml = pd.read_csv('test_db_ml_l2_2018.csv')
dfranknet = pd.read_csv('result-shorterm_l2_2018_pitmodel.csv')
carlist = set(list(dfml['carno'].values))
dfpits = []
for car in carlist:
    pitlaps = dfml[dfml['carno']==car].startlap
    dfpits.append(dfranknet[(dfranknet['carno']==car) & (dfranknet['startlap'].isin(pitlaps))])
    
df_ranknet = pd.concat(dfpits)
stint.get_evalret(df_ranknet)


model: acc={0.39}, mae={3.85}, rmse={5.85},r2={-16.47}, 
            naive: acc={0.26}, mae={3.73}, rmse={5.65},r2={0.58}


array([[  0.38993711,   3.8490566 ,   5.85463317, -16.47147062],
       [  0.26415094,   3.72955975,   5.65184892,   0.5774171 ]])

In [12]:
pitlaps = dfml[dfml['carno']==12].startlap
dfranknet[(dfranknet['carno']==12) & (dfranknet['startlap'].isin(pitlaps))]

Unnamed: 0  carno  startlap  startrank  endrank  diff  sign  \
700          700     12        31        3.0      9.0   6.0     1   
1284        1284     12        49        5.0      3.0  -2.0    -1   
2581        2581     12        93        0.0      8.0   8.0     1   
3576        3576     12       128        1.0      6.0   5.0     1   

      pred_endrank  pred_diff  pred_sign  
700            3.0        0.0          0  
1284           3.0       -2.0         -1  
2581           0.0        0.0          0  
3576           0.0       -1.0         -1

In [13]:
dfml[dfml['carno']==12]

Unnamed: 0  carno  startlap  startrank  endrank
33          33     12        31          3        9
34          34     12        49          5        3
35          35     12        93          0        8
36          36     12       128          1        6

In [19]:
carlist = set(list(dfml['carno'].values))
dfpits = []
for car in carlist:
    pitlaps = dfml[dfml['carno']==car].startlap
    dfpits.append(dfranknet[(dfranknet['carno']==car) & (dfranknet['startlap'].isin(pitlaps))])
    
df_ranknet = pd.concat(dfpits)
stint.get_evalret(df_ranknet)


In [20]:
df_ranknet[df_ranknet['carno']==12]

Unnamed: 0  carno  startlap  startrank  endrank  diff  sign  \
700          700     12        31        3.0      9.0   6.0     1   
1284        1284     12        49        5.0      3.0  -2.0    -1   
2581        2581     12        93        0.0      8.0   8.0     1   
3576        3576     12       128        1.0      6.0   5.0     1   

      pred_endrank  pred_diff  pred_sign  
700            3.0        0.0          0  
1284           3.0       -2.0         -1  
2581           0.0        0.0          0  
3576           0.0       -1.0         -1

In [21]:
df_ranknet

Unnamed: 0  carno  startlap  startrank  endrank  diff  sign  \
693          693      1        31        2.0      4.0   2.0     1   
1277        1277      1        49        2.0      4.0   2.0     1   
1879        1879      1        69        8.0     19.0  11.0     1   
2778        2778      1       100        8.0     20.0  12.0     1   
3738        3738      1       134        7.0     18.0  11.0     1   
...          ...    ...       ...        ...      ...   ...   ...   
4690        4690     88       170       16.0     18.0   2.0     1   
725          725     98        31        6.0     12.0   6.0     1   
1307        1307     98        49        9.0     12.0   3.0     1   
2545        2545     98        91       14.0     22.0   8.0     1   
3485        3485     98       124        9.0     20.0  11.0     1   

      pred_endrank  pred_diff  pred_sign  
693            5.0        3.0          1  
1277           2.0        0.0          0  
1879          18.0       10.0          1  
2778          13.0        5.0          1  
3738          14.0        7.0          1  
...            ...        ...        ...  
4690          18.0        2.0          1  
725            7.0        1.0          1  
1307           9.0        0.0          0  
2545          16.0        2.0          1  
3485          16.0        7.0          1  

[159 rows x 10 columns]

In [23]:
stint.get_evalret(df_ranknet)

model: acc={0.70}, mae={2.46}, rmse={4.37},r2={-0.66}, 
            naive: acc={0.26}, mae={3.73}, rmse={5.65},r2={0.58}


array([[ 0.70440252,  2.4591195 ,  4.37186545, -0.66177512],
       [ 0.26415094,  3.72955975,  5.65184892,  0.5774171 ]])