In [36]:
from mxnet import nd
import mxnet.symbol as F

In [12]:
a = nd.ones((32,12,1))

In [13]:
a[:,5,0] = 3
a[0,12,0] = 4


In [14]:
c = a[:,2:,0] - a[:,:-2,0]

In [17]:
a[:,5,0]


[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3.]
<NDArray 32 @cpu(0)>

In [19]:
c.shape

(32, 10)

In [20]:
a[:,2:,0]


[[1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1

In [21]:
 a[:,:-2,0]


[[1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 3. 1. 1. 1. 1.]
 [1. 1. 1

In [33]:
c = a[:,2:,0] - a[:,:-2,0]
c


[[ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -2.  0.  0.  0.  0.]
 [ 0.  0. 

In [34]:
w1 = nd.ones_like(c)
w9 = nd.ones_like(c)*9
nd.where(c==0,w1,w9)


[[1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1

In [37]:
c.shape

(32, 10)

## symbol api

In [46]:
a = F.ones((3,12))
c = F.ones((3,12))*9
b = nd.ones((12))
b[3] = 0
d = F.Variable(b)

TypeError: Expect a string for variable `name`

In [44]:
F.where(b==0, c,a)

AssertionError: Argument condition must be Symbol instances, but got 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
<NDArray 12 @cpu(0)>

In [47]:
x = [[  1.,   2.,   3.,   4.],
     [  5.,   6.,   7.,   8.],
     [  9.,  10.,  11.,  12.]]
F.slice_axis(x, axis=0, begin=1, end=3)

AssertionError: Argument data must be Symbol instances, but got [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]

In [61]:
import mxnet as mx
import numpy as np

x = np.array([[  1.,   1.,   3.,   4.],
     [  5.,   5.,   5.,   8.],
     [  9.,  10.,  10.,  10.]])

a = mx.sym.Variable('A')
w1 = mx.sym.Variable('w1')
w9  = mx.sym.Variable('w9')
executor = a.simple_bind(ctx=mx.cpu(), A=(3,4))
#executor.forward(A=np.ones((3,12)))
executor.forward(A=x)

[
 [[ 1.  1.  3.  4.]
  [ 5.  5.  5.  8.]
  [ 9. 10. 10. 10.]]
 <NDArray 3x4 @cpu(0)>]

In [62]:
r = F.slice_axis(a, axis=1, begin=2, end=None)
l = F.slice_axis(a, axis=1, begin=0, end=-2)
w1 = F.ones_like(r)
w9 = F.ones_like(r)*9
w = F.where(r==l, w1, w9)

In [71]:
executor = w0.simple_bind(ctx=mx.cpu(), A=(3,4))
#executor.forward(A=np.ones((3,12)))
executor.forward(A=x)

[
 [[1. 1. 9. 9.]
  [1. 1. 1. 9.]
  [1. 1. 9. 1.]]
 <NDArray 3x4 @cpu(0)>]

In [70]:
s = F.slice_axis(a, axis=1, begin=0, end=2)
z = F.ones_like(s)
w0 = F.concat(z, w)