In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
from numpy.random import normal
import tqdm
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import pickle

In [51]:
with open('savedata_drank_e1.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    data,target,other = pickle.load(f, encoding='latin1') 
    
    print('batch#:',len(data),len(target))

batch#: 100 100


In [52]:
target[0].shape

(32, 42)

In [53]:
other[0].shape

(32, 42, 22)

In [54]:
data[0].shape

(32, 42, 33)

In [55]:
target[4][0,:]

array([ 8., 15., 15., 14., 14., 14.,  9., 10., 10., 10.,  9.,  9.,  7.,
        8.,  9., 10., 10.,  9.,  9., 10., 10., 10., 10., 10., 10.,  9.,
        9., 10., 10., 10.,  9.,  9.,  9., 10., 11., 11., 11., 11., 11.,
       10., 10.,  9.], dtype=float32)

In [56]:
other[4][0,0,:]

array([3., 5., 8., 9., 9., 9., 9., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.], dtype=float32)

In [48]:
other[4][0,1,:]

array([17., 17., 17., 17., 17., 17., 15., 25., 25., 25., 25., 26., 26.,
       26., 26., 26., 26.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [57]:
other[4][0,0:5,:]

array([[ 3.,  5.,  8.,  9.,  9.,  9.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 8.,  3.,  5.,  8.,  9.,  9.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [15.,  8.,  3.,  5.,  8.,  9.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [15., 15.,  8.,  3.,  5.,  8.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [14., 15., 15.,  8.,  3.,  5.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [58]:
data[4][0,0,:]

array([ 0.29339853,  0.48899755,  0.7823961 ,  0.88019556,  0.88019556,
        0.88019556,  0.88019556,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.02542373, -0.5       , -0.33333334,
       -0.46666667, -0.49725273,  1.5185139 ,  0.        ,  1.        ,
       -1.0489738 ,  0.        ,  2.3248358 ], dtype=float32)

In [25]:
data[0][0,0,:]

array([ 0.82644624,  0.82644624,  0.82644624,  0.82644624,  0.74380165,
        0.82644624,  0.82644624,  0.82644624,  0.74380165,  0.74380165,
        0.74380165,  0.9090909 ,  0.9090909 ,  0.9090909 ,  0.9090909 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.5       , -0.41304347, -0.33333334,
       -0.46666667, -0.49725273,  2.0863597 ,  1.        ,  0.        ,
       -1.0510695 ,  0.        ,  2.4932055 ], dtype=float32)

In [9]:
data[0][0,1,:]

array([ 0.7475994 ,  0.7409347 ,  0.73414344,  0.7214499 ,  0.7134138 ,
        0.70263374,  0.6928824 ,  0.6041869 ,  0.59900564,  0.5905975 ,
        0.5823302 ,  0.5767546 ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.33050847, -0.45652175, -0.33333334,
       -0.46666667, -0.49725273,  2.045323  ,  0.        ,  0.        ,
       -1.0510695 ,  0.        ,  4.8990006 ], dtype=float32)

In [10]:
data[0][0,10,:]

array([ 1.6017139 ,  1.6592612 ,  1.7874302 ,  2.1499755 ,  1.8250135 ,
        1.3707234 ,  0.99618155,  0.7223996 ,  0.7156947 ,  0.69756645,
        0.6610716 ,  0.6519121 ,  0.43530324,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.48305085, -0.45652175, -0.33333334,
       -0.46666667, -0.49725273,  2.0791812 ,  1.        ,  0.        ,
       -1.0510695 ,  0.        ,  4.8990006 ], dtype=float32)